header:
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: Santiago Lizardo
    software-name: NeoCommander

  paths-ignore:
    - 'target'
    - '**/**.yaml'
    - '**/**.yml'
    - '**/**.properties'
    - '**/**.md'
    - '**/*.po'
    - '**/*.pot'
    - 'LICENSE'
